---

- name: Copy binary
  copy:
    src: "{{BITCOIVACLI_BINARY}}"
    dest: /usr/bin/bitcoivacli
    mode: 0755
  notify: restart bitcoivacli

- name: Copy service
  template:
    src: bitcoivacli.service.j2
    dest: /etc/systemd/system/bitcoivacli.service
  notify: systemctl

