---

- name: Stop service
  service: name=bitcoivad state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
  - /usr/bin/bitcoivad
  - /home/bitcoivad/.bitcoivad
  - /home/bitcoivad/.bitcoivacli

