---

- name: Fetch genesis.json
  fetch: "src=/home/bitcoivad/.bitcoivad/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bitcoivad

- name: Fetch config.toml
  fetch: "src=/home/bitcoivad/.bitcoivad/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bitcoivad

