init_config:

instances:
- name: ssh
  search_string: ['ssh', 'sshd']
  thresholds:
    critical: [1, 5]
- name: bitcoivad
  search_string: ['bitcoivad']
  thresholds:
    critical: [1, 1]
- name: bitcoivacli
  search_string: ['bitcoivacli']
  thresholds:
    critical: [1, 1]
